FROM nginx 
RUN rm -rf /usr/share/nginx/html/index.html
RUN rm -rf /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/nginx.conf
COPY static /usr/share/nginx/html/
COPY asset-manifest.json /usr/share/nginx/html/
COPY index.html /usr/share/nginx/html/
COPY robots.txt /usr/share/nginx/html/